export const CHANGE_EXCHANGE_RATES_API_KEY = 'CHANGE_EXCHANGE_RATES_API_KEY';

export const LOAD_EXCHANGE_RATES_REQUEST = 'LOAD_EXCHANGE_RATES_REQUEST';
export const LOAD_EXCHANGE_RATES_SUCCESS = 'LOAD_EXCHANGE_RATES_SUCCESS';
export const LOAD_EXCHANGE_RATES_FAILURE = 'LOAD_EXCHANGE_RATES_FAILURE';
